from arm64v8/alpine

RUN apk update && \
    apk add g++ boost-dev boost-static cmake czmq-dev qt6-qtbase-dev spdlog-dev nlohmann-json protobuf-dev \
    libjpeg sqlite-dev make zeromq-dev czmq-static qt6-qtbase-sqlite ninja clang-dev gdb gtest benchmark-dev \
    pugixml openssl-dev poco-dev